### ISSUE TITLE
create HomePage

### ISSUE THREAD

**Issue by jaiyankargupta** [Himasnhu-AT/travel-guide#2]
## Complete HomePage

create a homepage for site.

Homepage should have following sections: 
- header: intro to platform
- services/ features
- testimonials
- famous places / blogs/ articles
- footer: links to social media, internal Links

**Comment by Himasnhu-AT** [comment]
@jaiyankargupta 

Homepage has Following components:
- Hero Section: Introduce platform
- services
- features
- User Testimonials
