### ISSUE TITLE
Improve Signup and Login Pages

### ISSUE THREAD

**Issue by jaiyankargupta** [Himasnhu-AT/travel-guide#6]
1. **Clear Design**: Keep the design clean and straightforward, with easy-to-understand instructions.
2. **Mobile Friendly**: Ensure the pages work well on mobile devices for seamless access.
3. **Prominent Buttons**: Make signup and login buttons clearly visible and easy to click.
4. **Social Login**: Offer the option to sign up or log in using social media accounts.
5. **Password Strength**: Include a tool to help users create strong passwords.
6. **Error Handling**: Provide instant feedback on incorrect inputs with clear error messages.
7. **Privacy Statement**: Clearly state your privacy policy to reassure users.
8. **Forgot Password**: Offer a simple process for password recovery.
9. **Accessibility**: Ensure the pages are accessible to all users, including those with disabilities.
10. **Continuous Improvement**: Regularly update based on user feedback to enhance user experience.

**Comment by Himasnhu-AT** [comment]
@jaiyankargupta , no need to go with such details

#### Things for authpages:

- ###### Login:
- in form, we have email fields 

- ###### SignUp:
- in form, need to have name, username, email, other fields

> No need for password

After clicking on button, they'll be redirected to page which shows them to click on code that is emailed to them

**Comment by Himasnhu-AT** [comment]
@jaiyankargupta , update input label UI, and add login page
